###
POST {{base_url}}/demo/clear
Content-Type: application/json

###
POST {{base_url}}/demo/create-json
Content-Type: application/json

{
  "data": {
    "v1": "3",
    "v2": "2",
    "v3": "1",
    "v4": "5"
  }
}

###
POST {{base_url}}/demo/send/v1

###
POST {{base_url}}/demo/send/v2

###
POST {{base_url}}/demo/send/v3

###
POST {{base_url}}/demo/send/v4

###
@startDate = 2024-09-01
@endDate = 2024-09-25
@requesterIds = a1b2c3d4e5f6,1a2b3c4d5e6f

GET {{base_url}}/api/v1/acorn?startDate={{startDate}}&endDate={{endDate}}&requesterIds={{requesterIds}}

###
GET {{base_url}}/api/v1/statistics/summary?startDate={{startDate}}&endDate={{endDate}}&requesterIds={{requesterIds}}
